<a href="https://colab.research.google.com/github/freddy-7/TI2001B-2023/blob/main/1_Extracci%C3%B3n_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#INSTALAR LIBRERIAS
!pip install pandas
!pip install numpy
!pip install matplotlib
!pip install seaborn
!pip install openpyxl

Requirement already satisfied: pandas in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\alfre\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

Requirement already satisfied: numpy in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (1.26.4)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\alfre\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

Requirement already satisfied: matplotlib in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (3.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.4.5)
Requirement already satisfied: numpy>=1.23 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (1.26.4)
Requirement already satisfied: packaging>=20.0 in c:\users\alfre\appdata\roaming\python\python312\site-packages (from matplotlib) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\alfre\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

Requirement already satisfied: seaborn in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (0.12.2)
Requirement already satisfied: numpy!=1.24.0,>=1.17 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (1.26.4)
Requirement already satisfied: pandas>=0.25 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (2.2.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from seaborn) (3.9.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.2.1)
Requirement already satisfied: cycler>=0.10 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (4.53.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\users\alfre\appdata\roaming\python\python312\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (24.1)
Requirement already satisfied: pillow>=8 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (10.4.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from matplotlib!=3.6.1,>=3.1->seaborn) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.25->seaborn) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from pandas>=0.25->seaborn) (2024.1)
Requirement already satisfied: six>=1.5 in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.1->seaborn) (1.16.0)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\alfre\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\alfre\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (1.1.0)

[notice] A new release of pip is available: 24.2 -> 25.2
[notice] To update, run: C:\Users\alfre\AppData\Local\Programs\Python\Python312\python.exe -m pip install --upgrade pip

In [1]:
#Importamos librer√≠as requeridas
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#GOOGLE COLAB
#Cargar archivo csv desde equipo
from google.colab import files
files.upload()

CARGA DE ARCHIVO .CSV

In [3]:
#Convertir en dataframe
df_csv= pd.read_csv("file.csv")
df_csv

,Periodo,Trimestre,Entidad_Federativa,Sexo,Poblacion_ocupada_en_la_industria_manufacturera,Poblaci n_ocupada,Tasa_de_ocupaci n_en_la_industria_manufacturera
0,2005,1,Nacional,Hombres,4384907,26597801,16.485975660000000000000
1,2005,1,Nacional,Mujeres,2690296,14843275,18.124679360000000000000
2,2005,1,Aguascalientes,Hombres,56407,246177,22.913188480000000000000
3,2005,1,Aguascalientes,Mujeres,28430,145656,19.518591750000000000000
4,2005,1,Baja California,Hombres,167651,768989,21.801482210000000000000
...,...,...,...,...,...,...,...
4549,2022,1,Veracruz,Mujeres,107640,1190733,9.0398099320000000000000
4550,2022,1,Yucat n,Hombres,101992,691397,14.751582670000000000000
4551,2022,1,Yucat n,Mujeres,82759,478943,17.279509250000000000000
4552,2022,1,Zacatecas,Hombres,44105,402326,10.962503040000000000000
4553,2022,1,Zacatecas,Mujeres,39472,255761,15.43315830000000000000

CARGA DE ARCHIVO XLSX

In [2]:
#Carga desde un archivo .xlsx sin indice
df= pd.read_excel('Antig√ºedad de saldos 17.03.2023.xlsx')
df

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,P√öBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,P√öBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,P√öBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [3]:
#Verificamos informaci√≥n del DataFrame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 164 entries, 0 to 163
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   No. CLIENTE        164 non-null    object
 1   NOMBRE             164 non-null    object
 2   FACTURA            164 non-null    object
 3   FECHA_FACTURA      164 non-null    datetime64[ns]
 4   FECHA_VENCIMIENTO  164 non-null    datetime64[ns]
 5   MONTO ADEUDADO     164 non-null    float64
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 7.8+ KB

In [6]:
#Imprimo los primeros 5 registro del dataframe
df.head()

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80

**FILTROS BASICOS PARA VARIABLES CUALITATIVAS**

In [4]:
#Filtro por objeto
filtro1=df[df["NOMBRE"] == "INDUSTRIAS LANCERMEX"]
filtro1

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
12,3930,INDUSTRIAS LANCERMEX,F40114,2023-02-09,2023-03-11,35143.82

In [7]:
#Filtro por filas
filtro2= df.iloc[3:10,: ]           #Filas consecutivas
filtro2=df.iloc[ [8, 24, 100] , : ]  #Filas no consecutivas
filtro2

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
24,8708,TE.MEX AUTOMOTIVE,F40183,2023-02-20,2023-03-13,22956.40
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16

In [10]:
#Filtro por columnas
#filtro3=df.iloc[ : , 0:3]       #Columnas consecutivas
filtro3=df.iloc[ : , [1,4,5]]  #Columnas no consecutivas
filtro3

,NOMBRE,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,DONGA HWASUNG MEXICO,2023-03-26,97485.94
1,DONGA HWASUNG MEXICO,2023-04-13,97485.94
2,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,2023-04-13,64916.21
3,INDUSTRIAS LANCERMEX,2023-03-25,52715.74
4,HELVEX,2023-04-03,50639.80
...,...,...,...
159,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,2023-01-31,56.00
160,P√öBLICO EN GENERAL,2023-03-07,45.00
161,P√öBLICO EN GENERAL,2023-03-09,40.00
162,P√öBLICO EN GENERAL,2023-03-09,24.01
163,FISHERS QUERETARO,2022-05-27,19.94

In [ ]:
#GOOGLE COLAB
#Filtro de filas vs columnas
#Paso 1: Leemos el contenido del archivo
from google.colab import files
uploaded=files.upload()

In [8]:
df1= pd.read_excel('Antig√ºedad de saldos 17.03.2023.xlsx', index_col=1)
df1

,No. CLIENTE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
NOMBRE,,,,,
DONGA HWASUNG MEXICO,6401,F40238,2023-02-24,2023-03-26,97485.94
DONGA HWASUNG MEXICO,6401,F40353,2023-03-14,2023-04-13,97485.94
PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,4598,F40352,2023-03-14,2023-04-13,64916.21
INDUSTRIAS LANCERMEX,3930,F40217,2023-02-23,2023-03-25,52715.74
HELVEX,4712,F40173,2023-02-17,2023-04-03,50639.80
...,...,...,...,...,...
CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADOS DEL INSTITUTO POLITECNICO NACIONAL,856,F40055,2023-01-31,2023-01-31,56.00
P√öBLICO EN GENERAL,5926,NV00777,2023-03-07,2023-03-07,45.00
P√öBLICO EN GENERAL,5926,NV00778,2023-03-09,2023-03-09,40.00
P√öBLICO EN GENERAL,5926,NV00779,2023-03-09,2023-03-09,24.01
FISHERS QUERETARO,8429,F38248,2022-05-27,2022-05-27,19.94

In [9]:
#Paso 2: Aplicamos Filtro de filas vs columnas
filtro4=df1.loc[["HELVEX","DONGA HWASUNG MEXICO"], ["MONTO ADEUDADO"]]
filtro4

                      MONTO ADEUDADO
NOMBRE
HELVEX                      50639.80
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        97485.94
DONGA HWASUNG MEXICO        10759.00
DONGA HWASUNG MEXICO         9396.00

In [13]:
#Filtro por cabecera
filtro5=df.head(10)
filtro5

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
0,6401,DONGA HWASUNG MEXICO,F40238,2023-02-24,2023-03-26,97485.94
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
3,3930,INDUSTRIAS LANCERMEX,F40217,2023-02-23,2023-03-25,52715.74
4,4712,HELVEX,F40173,2023-02-17,2023-04-03,50639.80
5,1429,AUTOLIV STEERING WHEELS MEXICO,F39979,2023-01-24,2023-03-25,49416.00
6,1429,AUTOLIV STEERING WHEELS MEXICO,F40319,2023-03-08,2023-05-07,49416.00
7,5039,BUSSMANN,F40082,2023-02-04,2023-02-04,48882.12
8,644,CLAVOS NACIONALES C.N,F40340,2023-03-13,2023-05-12,45216.34
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34

**FILTROS BASICOS PARA VARIABLES CUANTITATIVAS**

In [11]:
#Filtro por comparacion
filtro6=df[df["MONTO ADEUDADO"] < 1000]
filtro6

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
131,5926,P√öBLICO EN GENERAL,NV00356,2021-08-16,2021-08-16,815.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
133,2549,MARATHON SYSTEMS CONTROL,F39912,2023-01-12,2023-02-11,765.60
134,8434,FRANCISCO JAVIER MEDINA SANCHEZ,F39426,2022-10-27,2022-10-27,763.04
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
136,5598,MECAPRIM SERVICIOS INDUSTRIALES,F40369,2023-03-15,2023-03-15,742.40
137,6746,JOSE ALEJANDRO DIAZ NIETO,F40336,2023-03-10,2023-03-10,730.01
138,8545,JV AGRO,F40373,2023-03-15,2023-03-15,704.41
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96
140,O,POLIETILENOS Y PRODUCTOS DE QUERETARO,F40374,2023-03-16,2023-03-16,658.60
141,5926,P√öBLICO EN GENERAL,NV00351,2021-08-06,2021-08-06,591.60
142,8564,DISTRIBUIDORA LIVERPOOL,F40348,2023-03-13,2023-03-13,568.40
143,357,TRATAMIENTOS TERMICOS DE QUERETARO,F39931,2023-01-17,2023-02-01,555.19
144,5926,P√öBLICO EN GENERAL,F36620,2021-11-09,2021-11-09,500.00
145,6885,CAPTIVE SPORT,F36062,2021-09-06,2021-09-06,500.00
146,7059,HEVACSA TERMOENCOGIBLES,F40311,2023-03-07,2023-03-07,487.20
147,8697,ELECTRO FERRETERA REAL,F40314,2023-03-08,2023-03-08,487.20
148,8243,SCIMPLA,F38125,2022-05-10,2022-05-10,420.00
149,8826,ANA KARLA ROSALES VAZQUEZ,F40097,2023-02-07,2023-02-07,406.00
150,161,LBQ FOUNDRY,F40161,2023-02-16,2023-03-18,366.04
151,8863,MANUFACTURERA SLY,F40334,2023-03-10,2023-03-10,313.50
152,5926,P√öBLICO EN GENERAL,NV00368,2021-08-26,2021-08-26,300.00
153,3011,J H MILLS,F40310,2023-03-07,2023-03-07,262.74
154,5926,P√öBLICO EN GENERAL,F35996,2021-08-31,2021-08-31,200.00
155,5936,BURBUPAC DE QUERETARO,F40318,2023-03-08,2023-04-07,191.04
156,6048,AT Y V DESARROLLOS Y MANUFACTURAS,F40370,2023-03-15,2023-03-15,139.20
157,5926,P√öBLICO EN GENERAL,NV00780,2023-03-13,2023-03-13,130.00
158,8698,OLMO RACKS & DUNNAGE,F38473,2022-06-28,2022-06-28,87.35
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,P√öBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,P√öBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,P√öBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

**FILTROS BASICOS CON CONETORES LOGICOS**

In [12]:
#Filtro Y
filtro7=df[(df["MONTO ADEUDADO"] < 6000) & (df["FECHA_FACTURA"] == "2023-03-14")]
filtro7

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
85,409,CONSTRUCCIONES ELECTROMECANICAS Y SERVICIOS IN...,F40359,2023-03-14,2023-03-14,4292.00
96,3926,PRODUCTOS PENNSYLVANIA,F40358,2023-03-14,2023-04-13,3368.64
100,3926,PRODUCTOS PENNSYLVANIA,F40357,2023-03-14,2023-04-13,2756.16
101,5926,P√öBLICO EN GENERAL,F40362,2023-03-14,2023-03-14,2694.95
113,2216,FRESCOPACK,F40355,2023-03-14,2023-03-14,1682.00
132,1284,TERMOFORMADOS,F40349,2023-03-14,2023-04-13,799.24
135,8872,GABRIELA GARCIA SANCHEZ,F40360,2023-03-14,2023-03-14,754.00
139,8228,UCH COMERCIAL,F40365,2023-03-14,2023-03-14,702.96

In [13]:
#Filtro o
filtro8=df[(df["MONTO ADEUDADO"] < 6000) | (df["FECHA_FACTURA"] == "2023-03-14")]
filtro8

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
1,6401,DONGA HWASUNG MEXICO,F40353,2023-03-14,2023-04-13,97485.94
2,4598,PROVEEDORA DE SEGURIDAD INDUSTRIAL DEL GOLFO,F40352,2023-03-14,2023-04-13,64916.21
9,644,CLAVOS NACIONALES C.N,F40351,2023-03-14,2023-05-13,45216.34
10,3937,RICHALUM,F40361,2023-03-14,2023-03-14,42880.05
36,417,COVEMEX,F40354,2023-03-14,2023-03-29,15843.28
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,P√öBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,P√öBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,P√öBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [15]:
#Filtro not
filtro9=df[~(df["MONTO ADEUDADO"] >= 6000)]
filtro9

,No. CLIENTE,NOMBRE,FACTURA,FECHA_FACTURA,FECHA_VENCIMIENTO,MONTO ADEUDADO
70,1852,ITW POLY MEX,F40201,2023-02-22,2023-03-24,5967.85
71,8316,ANA BARBARA CRUZ PALACIOS,F40379,2023-03-16,2023-03-31,5827.84
72,8787,ARMANDO VIDAURRETA PE√ëA,F39769,2022-12-14,2022-12-14,5800.00
73,2768,CEREALES Y PASTAS,F40215,2023-02-22,2023-03-24,5660.80
74,1831,DISTRIBUCIONES Y REPRESENTACIONES CALORA,F40316,2023-03-08,2023-04-22,5502.81
...,...,...,...,...,...,...
159,856,CENTRO DE INVESTIGACION Y DE ESTUDIOS AVANZADO...,F40055,2023-01-31,2023-01-31,56.00
160,5926,P√öBLICO EN GENERAL,NV00777,2023-03-07,2023-03-07,45.00
161,5926,P√öBLICO EN GENERAL,NV00778,2023-03-09,2023-03-09,40.00
162,5926,P√öBLICO EN GENERAL,NV00779,2023-03-09,2023-03-09,24.01
163,8429,FISHERS QUERETARO,F38248,2022-05-27,2022-05-27,19.94

In [16]:
#Convertir archivo filtrado a CSV
filtro9.to_csv("FiltroNot.csv")

In [ ]:
#GOOGLE COLAB
#descardar archivo filtrado en csv
from google.colab import files


files.download("Entregable1.csv")